language: java
jdk:
    - openjdk8
branches:
    only:
        - master

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.maven'

script: "./mvnw clean package"

before_deploy: 
  - zip -r nomad-hackathon-backend * 
  - mkdir -p deploy 
  - mv nomad-hackathon-backend.zip deploy/nomad-hackathon-backend.zip 


deploy: 
  - provider: s3 
    access_key_id: $AWS_ACCESS_KEY 
    secret_access_key: $AWS_SECRET_KEY 
    bucket: printboard-backend-deploy
    region: ap-northeast-2
    local_dir: deploy

    skip_cleanup: true 
    acl: public_read 
    wait-until-deployed: true 
    on: 
        repo: seulgiwendy/nomad-hackathon-backend
        branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: printboard-backend-deploy
    key: deploy/nomad-hackathon-backend.zip
    bundle_type: zip
    application: codesquad-library
    deployment_group: codesquad-library-backend
    region: ap-northeast-2
    wait-until-deployed: true
    on:
        repo: seulgiwendy/nomad-hackathon-backend
        branch: master


notifications:
    email:
        recipients:
        - me@wheejuni.com
    slack: 
        codesquad-members:t7B1WHfsCgrRfipipWXNLKnQ
