spring:
  profiles:
    active: local

---

spring:
  profiles: local
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:~/my-jwp2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    data-password:

oauth:
  client:
    id: printboard-api
  resource:
    id: printboard-resource
  access_token:
    signingkey: printboard

